# Generated by Django 4.0.1 on 2022-01-23 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task3_print_invoices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_name', models.CharField(max_length=44)),
                ('product', models.CharField(max_length=130)),
                ('company', models.CharField(max_length=44)),
                ('ship_date', models.DateTimeField()),
                ('ordered_warranty', models.BooleanField()),
            ],
        ),
        migrations.DeleteModel(
            name='Orders',
        ),
    ]
