# Generated by Django 4.0.1 on 2022-01-23 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task3_print_invoices', '0003_alter_order_ordered_warranty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='person_name',
            field=models.CharField(blank=True, max_length=44, null=True),
        ),
    ]
