# Generated by Django 4.0.1 on 2022-01-23 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task3_print_invoices', '0004_alter_order_person_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='person_name',
            field=models.CharField(default='Az', max_length=44),
            preserve_default=False,
        ),
    ]
