# Generated by Django 4.0.1 on 2022-01-27 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task4_blog_django_3_by_example', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('something', models.CharField(max_length=17)),
            ],
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-publish',)},
        ),
    ]
