# Generated by Django 4.0.1 on 2022-02-02 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task4_blog_django_3_by_example', '0002_test_alter_post_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
